spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: src/main/scripts/schemacreate.sql
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/forecast_dev
    username: sample_user
    password: testpw
    driverClassName: org.postgresql.Driver