# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: maven:3.5.0-jdk-8
        environment:
          DATABASE_URL: jdbc:postgresql://127.0.0.1:5432/forecast_dev
          DATABASE_USER: sample_user
          DATABASE_PASSWORD: testpw
      - image: postgres:9.6

    working_directory: ~/repo

    steps:
      - checkout
      - run: apt-get update -qq && apt-get install -y postgresql
      - run:
          command: |
            psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE forecast_dev;"
      - run:
          command: |
            psql -h 127.0.0.1 -U postgres -d forecast_dev -c "CREATE USER sample_user WITH
            PASSWORD 'testpw';"
      - run:
          command: |
            psql -h 127.0.0.1 -U postgres -d forecast_dev -c "REVOKE CREATE ON SCHEMA public FROM
            public;"
      - run:
          command: |
            psql -h 127.0.0.1 -U postgres -d forecast_dev -c "ALTER DEFAULT PRIVILEGES in SCHEMA
            public GRANT SELECT ON TABLES TO sample_user;"
      - run:
          command: |
            psql -h 127.0.0.1 -U postgres -d forecast_dev -c "ALTER DEFAULT PRIVILEGES in SCHEMA
            public GRANT DELETE ON TABLES TO sample_user;"
      - run:
          command: |
            psql -h 127.0.0.1 -U postgres -d forecast_dev -c "ALTER DEFAULT PRIVILEGES in SCHEMA
            public GRANT UPDATE ON TABLES TO sample_user;"
      - run:
          command: |
            psql -h 127.0.0.1 -U postgres -d forecast_dev -c "ALTER DEFAULT PRIVILEGES in SCHEMA
            public GRANT INSERT ON TABLES TO sample_user;"
      - run:
          command: |
            psql -h 127.0.0.1 -U postgres -d forecast_dev -c "create table custom_user_role
            (custom_user_id int8 not null, role_id int8 not null, primary key (custom_user_id,
            role_id));"
      - run:
          command: |
            psql -h 127.0.0.1 -U postgres -d forecast_dev -c "create table custom_user (id
            bigserial not null, date_created timestamp, last_updated timestamp, enabled boolean,
            encrypted_password varchar(255), username varchar(255), primary key (id));"

      - run: mvn integration-test

      # hook to send to codecov.
      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)