# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: maven:3.5.0-jdk-8
        environment:
          DATABASE_URL: jdbc:postgresql://127.0.0.1:5432/forecast_dev
          DATABASE_USER: username
          DATABASE_PASSWORD: password
      - image: postgres:9.6

    working_directory: ~/repo

    steps:
      - checkout
      - run: apt-get update -qq && apt-get install -y postgresql
      - run:
          command: |
            psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE forecast_dev;"
            psql -h 127.0.0.1 -U postgres -c "CREATE USER username WITH PASSWORD 'password';
            GRANT ALL PRIVILEGES ON DATABASE forecast_dev TO username;"

      - run: mvn test

      # hook to send to codecov.
      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)