# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: circleci/postgres:9.6

    working_directory: ~/tt-j-weatherforecast

    environment: # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-9.6
      - run: sudo service postgresql start
      - run: |
          psql \
          -h 127.0.0.1
          -U postgres
          -c "CREATE DATABASE forecast_dev;"
          psql \
          -h 127.0.0.1
          -U postgres
          -c "CREATE USER sample_user WITH PASSWORD 'testpw';"
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run IT tests
      - run: mvn integration-test

      - store_test_results:
          path: target/surefire-reports

      # hook to send to codecov.
      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)